blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailings.apps import MailingsConfig
from mailings.views import *

app_name = MailingsConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('mailings/list/', cache_page(60)(MailingsListView.as_view()), name='mailings_list'),
    path('mailings/<int:pk>/', MailingsDetailView.as_view(), name='mailings_detail'),
    path('mailings/create/', MailingsCreateView.as_view(), name='mailings_create'),
    path('mailings/<int:pk>/update/', MailingsUpdateView.as_view(), name='mailings_update'),
    path('mailings/<int:pk>/delete/', MailingsDeleteView.as_view(), name='mailings_delete'),
    path('client/', cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('contacts/', ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('message/', cache_page(60)(MessageListView.as_view()), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    path('mailings/<int:pk>/toggle_activity', toggle_activity, name='mailing_toggle_activity'),
    path('logs/', LogListView.as_view(), name='logs'),
    path('logs/<int:pk>/', get_mailing_logs, name='mailing_logs'),
    path('contacts/', ContactsView.as_view(), name='contacts')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, reset_password, verify_email, UserListView, toggle_activity

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('verify/<str:token>/', verify_email, name='verify'),
    path('reset_password/', reset_password, name='reset_password'),
    path('user/', UserListView.as_view(), name='list'),
    path('activity/<int:user_id>', toggle_activity, name='toggle_activity'),
    ]

blog/models.py
from django.db import models
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    content = models.TextField(verbose_name='Содержимое')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата публикации')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title} (создано {self.created_at})'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

mailings/models.py
from django.contrib.auth import get_user_model
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='email')
    fullname = models.CharField(max_length=150, verbose_name='Клиент')
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, verbose_name='Клиент', **NULLABLE)

    def __str__(self):
        return f'{self.fullname} ({self.email})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Mailings(models.Model):
    class Frequency(models.TextChoices):
        DAILY = 'daily', 'Раз в день'
        WEEKLY = 'weekly', 'Раз в неделю'
        MONTHLY = 'monthly', 'Раз в месяц'

    class Status(models.TextChoices):
        COMPLETED = 'completed', 'Завершена'
        CREATED = 'created', 'Создана'
        RUNNING = 'running', 'Запущена'

    name = models.CharField(max_length=200, verbose_name='Название рассылки', **NULLABLE)
    start_date = models.DateField(default=False, verbose_name='Дата рассылки')
    time = models.TimeField(default='00:00', verbose_name='Время рассылки')
    frequency = models.CharField(max_length=50, choices=Frequency.choices, verbose_name='Периодичность')
    status = models.CharField(max_length=50, choices=Status.choices, default=Status.CREATED,
                              verbose_name='Статус рассылки')
    clients = models.ManyToManyField(Client, verbose_name='Получатели')
    is_active = models.BooleanField(default=True, verbose_name='Активность рассылки')
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, verbose_name='Пользователь', **NULLABLE)
    message = models.ForeignKey('Message', on_delete=models.CASCADE, verbose_name='Сообщение')

    def __str__(self):
        return f'{self.name}({self.pk}): {self.get_frequency_display()}, {self.get_status_display()}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('-id',)
        permissions = [
            (
                'change_activity',
                'Change activity'
            )
        ]


class Message(models.Model):
    subject = models.CharField(max_length=100, verbose_name='Тема письма', **NULLABLE)
    content = models.TextField(verbose_name='Содержание', **NULLABLE)
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Письмо'
        verbose_name_plural = 'Письма'
        ordering = ('-id',)


class Log(models.Model):
    class Status(models.TextChoices):
        SUCCESS = 'success', 'Успешно'
        FAILURE = 'failure', 'Ошибка'

    datetime = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней попытки')
    status = models.CharField(max_length=10, choices=Mailings.Status.choices, verbose_name='Статус попытки')
    server_response = models.TextField(verbose_name='Ответ сервера', **NULLABLE)
    mailing = models.ForeignKey(Mailings, on_delete=models.CASCADE, verbose_name='Рассылка')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, default=0, verbose_name='Письмо')

    def __str__(self):
        return f'Рассылка {self.mailing}, статус: {self.status}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'
        ordering = ('-id',)

mailings/views.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView, TemplateView

from mailings.forms import MailingsForm, MessageForm, ClientForm
from mailings.models import Mailings, Message, Client, Log
from mailings.services import get_random_blog_article


class UserQuerysetMixin:
    """Ограничивает список просматриваемых пользователем объектов, принадлежащими только текущему пользователю,
     и сохраняет доступ для персонала"""

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_staff:
            return queryset
        return queryset.filter(user=self.request.user)


class StaffUserObjectMixin:
    """Ограничивает доступ пользователя к чужим объектам, и сохраняет доступ для персонала"""

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object


class UserObjectMixin:
    """Ограничивает доступ пользователя к чужим объектам"""

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_superuser:
            raise Http404
        return self.object


class UserFormMixin:
    """Присваивает объект пользователю"""

    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class LoginRequiredMessageMixin(LoginRequiredMixin):
    """Ограничение доступа для неавторизованных пользователей, вывод сообщения"""

    def handle_no_permission(self):
        messages.error(self.request, 'Для доступа к этой странице необходимо авторизоваться')
        return super().handle_no_permission()


def index(request):
    all_mailings = Mailings.objects.count()
    active_mailings = Mailings.objects.filter(is_active=True,
                                              status__in=[Mailings.Status.CREATED,
                                                          Mailings.Status.RUNNING]).count()
    clients = Client.objects.all().values('email').distinct().count()
    random_blog_article = get_random_blog_article()
    context = {
        'all_mailings': all_mailings,
        'active_mailings': active_mailings,
        'clients': clients,
        'blog_list': random_blog_article,
    }
    return render(request, 'mailings/index.html', context=context)


class ContactsView(TemplateView):
    template_name = 'mailings/clients_list.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.method == 'POST':
            name = self.request.POST.get('name')
            email = self.request.POST.get('email')
            message = self.request.POST.get('message')
            print(f'You have new message from {name}({email}): {message}')
        context_data['object_list'] = Client.objects.all()
        return context_data


class MailingsCreateView(LoginRequiredMessageMixin, PermissionRequiredMixin, UserFormMixin, CreateView):
    model = Mailings
    form_class = MailingsForm
    permission_required = 'mailings.add_mailings'
    success_url = reverse_lazy('mailings:mailings_list')

    def get_form(self, form_class=None):
        """Формирование полей, принадлежащих текущему пользователю"""
        form = super().get_form(form_class)
        form.fields['clients'].queryset = Client.objects.filter(user=self.request.user)
        form.fields['message'].queryset = Message.objects.filter(user=self.request.user)

        return form


class MailingsUpdateView(LoginRequiredMessageMixin, PermissionRequiredMixin, UserObjectMixin, UpdateView):
    model = Mailings
    form_class = MailingsForm
    permission_required = 'mailings.change_mailings'

    def get_success_url(self):
        return reverse('mailings:mailings_detail', args=[self.kwargs.get('pk')])


class MailingsListView(LoginRequiredMessageMixin, PermissionRequiredMixin, UserQuerysetMixin, ListView):
    model = Mailings
    permission_required = 'mailings.view_mailings'


class MailingsDetailView(LoginRequiredMessageMixin, PermissionRequiredMixin, StaffUserObjectMixin, DetailView):
    model = Mailings
    permission_required = 'mailings.view_mailings'


class MailingsDeleteView(LoginRequiredMessageMixin, PermissionRequiredMixin, UserObjectMixin, DeleteView):
    model = Mailings
    permission_required = 'mailings.delete_mailings'
    success_url = reverse_lazy('mailings:mailings_list')


class MessageCreateView(LoginRequiredMessageMixin, PermissionRequiredMixin, UserFormMixin, CreateView):
    model = Message
    form_class = MessageForm
    permission_required = 'mailings.add_message'
    success_url = reverse_lazy('mailings:message_list')


class MessageUpdateView(LoginRequiredMessageMixin, PermissionRequiredMixin, UserObjectMixin, UpdateView):
    model = Message
    form_class = MessageForm
    permission_required = 'mailings.change_message'

    def get_success_url(self):
        return reverse('mailings:message_detail', args=[self.kwargs.get('pk')])


class MessageListView(LoginRequiredMessageMixin, PermissionRequiredMixin, UserQuerysetMixin, ListView):
    model = Message
    permission_required = 'mailings.view_message'


class MessageDeleteView(LoginRequiredMessageMixin, PermissionRequiredMixin, UserObjectMixin, DeleteView):
    model = Message
    permission_required = 'mailings.delete_message'
    success_url = reverse_lazy('mailings:message_list')


class MessageDetailView(LoginRequiredMessageMixin, PermissionRequiredMixin, StaffUserObjectMixin, DetailView):
    model = Message
    permission_required = 'mailings.view_message'


class ClientCreateView(LoginRequiredMessageMixin, PermissionRequiredMixin, UserFormMixin, CreateView):
    model = Client
    form_class = ClientForm
    permission_required = 'mailings.add_client'
    success_url = reverse_lazy('mailings:client_list')


class ClientUpdateView(LoginRequiredMessageMixin, PermissionRequiredMixin, UserObjectMixin, UpdateView):
    model = Client
    form_class = ClientForm
    permission_required = 'mailings.change_client'

    def get_success_url(self):
        return reverse('mailings:client_detail', args=[self.kwargs.get('pk')])


class ClientListView(LoginRequiredMessageMixin, PermissionRequiredMixin, UserQuerysetMixin, ListView):
    model = Client
    permission_required = 'mailings.view_client'


class ClientDetailView(LoginRequiredMessageMixin, PermissionRequiredMixin, StaffUserObjectMixin, DetailView):
    model = Client
    permission_required = 'mailings.view_client'


class ClientDeleteView(LoginRequiredMessageMixin, PermissionRequiredMixin, UserObjectMixin, DeleteView):
    model = Client
    permission_required = 'mailings.delete_client'
    success_url = reverse_lazy('mailings:client_list')


@login_required
@permission_required('mailings.change_activity')
def toggle_activity(request, pk):
    """Отключение рассылок"""
    mailings = get_object_or_404(Mailings, pk=pk)
    if request.user.is_staff:
        if mailings.is_active:
            mailings.is_active = False
            mailings.status = mailings.Status.COMPLETED
            mailings.save()
        else:
            mailings.is_active = True
            mailings.status = mailings.Status.RUNNING
            mailings.save()
        return redirect('mailings:mailings_list')


class LogListView(LoginRequiredMessageMixin, ListView):
    model = Log

    def get_queryset(self):
        """Получает список логов рассылок принадлежащих только текущему пользователю, и всех логов для персонала"""
        queryset = super().get_queryset()
        if self.request.user.is_staff:
            return queryset
        return queryset.filter(mailing__user=self.request.user)


@login_required
def get_mailing_logs(request, pk):
    """Получение логов принадлежащих конкретной рассылке"""
    mailings_logs = Log.objects.filter(mailing_id=pk)
    mailings = mailings_logs.first().mailing
    context = {
        'object_list': mailings_logs,
        'mailings_name': mailings.name
    }
    return render(request, 'mailings/mailings_logs.html', context=context)

mailings/templates/mailings/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">SkyMailings</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="/mailings/list/">Каталог Рассылок</a>
        <a class="p-2 btn btn-outline-primary" href="/blog/">Блог</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'mailings:mailings_create' %}">Создать рассылку</a>
        {% else %}
        {% endif %}
        {% if request.user.is_staff %}
            <a class="p-2 btn btn-outline-primary {% if request.path == users_list_url %} active{% endif %}" href="{% url 'users:list' %}">Список пользователей</a>
        {% endif %}
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>


<div class="container">

{% block content %}
{% endblock %}
<footer class="pt-3 my-md-5 pt-md-2 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <a href="#">В начало</a>

                <p class="float-end mb-1"></p>
                <p class="mb-1">SkyMailings&copy; 2023</p>

            </div>
            <div class="col-6 col-md">
                <h5>Статистика сайта</h5>
                <ul class="list-unstyled text-small">
                    <li>Рассылок всего: {{ all_mailings }}</li>
                    <li>Активных рассылок: {{ active_mailings }}</li>
                    <li>Уникальных клиентов для рассылок: {{ clients }}</li>
                </ul>
            </div>
        </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailings/templates/mailings/client_detail.html
{% extends 'mailings/base.html' %}

{% block content %}

    <div class="container">
        <div class="row ">
            <div class="col-2">
                <a href="{% url 'mailings:client_list' %}" class="btn btn-primary mb-3">Вернуться к списку
                    клиентов</a>
            </div>
        </div>
        <div class="card w-50">
            <div class="card-header text-center">Клиент №{{ object.pk }}</div>
            <div class="card-body">
                <h5 class="card-title">Имя: {{ object.fullname }}</h5>
                <hr>
                <p class="card-text">Электронная почта: <br> {{ object.email }}</p>
                <hr>
                <p class="card-text">Комментарий: <br> {{ object.comment }}</p>
                {% if request.user.is_staff %}
                <hr>
                    <p class="card-text text-muted">Создал: <br> {{ object.user }}</p>
                {% endif %}
            </div>
            <div class="card-footer text-center">
                {% if perms.mailings.change_client %}
                    <a class="card-link mx-4" href="{% url 'mailings:client_update' object.pk %}">Изменить</a>
                {% endif %}
                {% if perms.mailings.delete_client %}
                    <a class="btn btn-danger m"
                       href="{% url 'mailings:client_delete' object.pk %}">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

mailings/templates/mailings/index.html
{% extends 'mailings/base.html' %}
{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="text-center">Добро пожаловать в сервис рассылок SkyMailings</h1>
            </div>
        </div>
        <br>
        {% if user.is_authenticated %}
            </div>
            <div class="container my-5">
                <div class="row">
                    <div class="col-4">
                        {% if perms.mailings.add_mailings %}
                            <div class="card w-auto">
                                <div class="card-header">Создать Рассылку</div>
                                <div class="card-body">
                                    <p class="card-text">Вы можете создать новую рассылку сообщений или воспользоваться списком уже
                                        существующих рассылок</p>
                                    <a href="{% url 'mailings:mailings_create' %}" class="btn btn-primary">Создать</a>
                                    {% if perms.mailings.view_mailings %}
                                        <a href="{% url 'mailings:mailings_list' %}" class="btn btn-outline-primary">Список рассылок</a>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-4">

                        {% if perms.mailings.add_message %}
                            <div class="card w-auto">
                                <div class="card-header">Создать Сообщение</div>
                                <div class="card-body">
                                    <p class="card-text">Вы можете создать сообщение для рассылки или воспользоваться списком
                                        существующих сообщений</p>
                                    <a href="{% url 'mailings:message_create' %}" class="btn btn-primary">Создать</a>
                                    {% if perms.mailings.view_message %}
                                        <a href="{% url 'mailings:message_list' %}" class="btn btn-outline-primary">Список
                                        сообщений</a>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-4">
                        {% if perms.mailings.add_client %}
                            <div class="card">
                                <div class="card-header">Добавить Получателей</div>
                                <div class="card-body">
                                    <p class="card-text">Вы можете добавить получателей рассылки или воспользоваться списком существующих клиентов</p>
                                    <a href="{% url 'mailings:client_create' %}" class="btn btn-primary">Создать</a>
                                    {% if perms.mailings.view_client %}
                                        <a href="{% url 'mailings:client_list' %}" class="btn btn-outline-primary">Список
                                        клиентов</a>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
    <div class="container">
        <div class="row mt-4">
            {% for object in blog_list %}
                <div class="col-4" style="width: 20rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.title }}</h5>
                        <p class="card-text">{{ object.content|slice:100 }}</p>
                        <p class="card-text text-muted">Количество просмотров: {{ object.views_count }}</p>
                        <span class="text-muted">Опубликовано: {{ object.created_at }}</span>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-primary"
                           href="{% url 'blog:view' object.pk %}">Просмотреть</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

mailings/templates/mailings/mailings_detail.html
{% extends 'mailings/base.html' %}

{% block content %}

    <div class="container">
        <div class="row ">
            <div class="col-2">
                <a href="{% url 'mailings:mailings_list' %}" class="btn btn-primary mb-3">Вернуться к списку
                    рассылок</a>
            </div>
        </div>
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header text-center">Рассылка №{{ object.pk }}</div>
                    <div class="card-body">
                        <h5 class="card-title">Название: {{ object.mailing_name }}</h5>
                        <hr>
                        <p class="card-text">Дата выполнения рассылки: {{ object.start_date }}</p>
                        <p class="card-text">Время выполнения рассылки: {{ object.time }}</p>
                        <p class="card-text">Периодичность: {{ object.get_frequency_display }}</p>
                        <p class="card-text">Статус рассылки: {{ object.get_status_display }}</p>
                        <hr>
                        <p class="card-text">Клиенты: </p>
                        <ul class="list-inline">
                            {% for client in object.clients.all %}
                                <li>{{ client.fullname }} - {{ client.email }}</li>
                            {% endfor %}
                        </ul>
                        <hr>
                        <p>
                            <a href="{% url 'mailings:message_detail' object.message_id %}">Сообщение
                                {{ object.message.subject }}</a>
                        </p>
                        <hr>
                        {% if request.user.is_staff %}
                            <p class="text-muted">Создал: {{ object.user }}</p>
                        {% endif %}
                    </div>
                    <div class="card-footer text-center">
                        {% if perms.mailings.change_mailings %}
                            <a class="card-link mx-4"
                               href="{% url 'mailings:mailings_update' object.pk %}">Изменить</a>
                        {% endif %}
                        {% if perms.mailings.delete_mailings %}
                            <a class="btn btn-danger m"
                               href="{% url 'mailings:mailings_delete' object.pk %}">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailings/templates/mailings/mailings_list.html
{% extends 'mailings/base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
                <div class="col-3">
                    <a href="{% url 'mailings:mailings_create' %}" class="btn btn-primary">Создать рассылку</a>
                </div>
            <div class="col-3">
                <a href="{% url 'mailings:logs' %}" class="btn btn-primary">Отчет</a>
            </div>
        </div>

        <div class="row my-5">
            {% for object in object_list %}
                <div class="card mb-4 mx-2" style="width: 20rem;">
                    <div class="card-header">Рассылка №{{ object.pk }}</div>
                    <div class="card-body">
                        <h5 class="card-title">Название: {{ object.name }}</h5>
                        <p class="card-text">Дата: {{ object.start_date }}</p>
                        <p class="card-text">Время: {{ object.time }}</p>
                        <p class="card-text">Статус: {{ object.get_status_display }}</p>
                        {% if request.user.is_staff %}
                            <span class="text-muted">Создал: {{ object.user }}</span>
                        {% endif %}
                    </div>
                    {% if perms.mailings.view_mailings %}
                        <div class="card-footer">
                            <a class="btn btn-primary" href="{% url 'mailings:mailings_detail' object.pk %}">Выбрать</a>
                            {% if perms.mailings.change_activity %}
                                {% if object.is_active %}
                                    <a class="btn btn-danger" href="{% url 'mailings:mailing_toggle_activity' object.pk %}">Отключить</a>
                                {% else %}
                                    <a class="btn btn-success" href="{% url 'mailings:mailing_toggle_activity' object.pk %}">Включить</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

mailings/templates/mailings/message_detail.html
{% extends 'mailings/base.html' %}

{% block content %}

    <div class="container">
        <div class="row ">
            <div class="col-2">
                <a href="{% url 'mailings:message_list' %}" class="btn btn-primary mb-3">Вернуться к списку
                    сообщений</a>
            </div>
        </div>
        <div class="card w-75">
            <div class="card-header text-center">Сообщение №{{ object.pk }}</div>
            <div class="card-body">
                <h5 class="card-title">Тема сообщения: <br>{{ object.subject }}</h5>
                <hr>
                <p class="card-text">Текст сообщения: <br> {{ object.body }}</p>
                <hr>
                {% if request.user.is_staff %}
                    <p class="text-muted">Создал: {{ object.user }}</p>
                {% endif %}
            </div>
            <div class="card-footer text-center">
                {% if perms.mailings.change_message %}
                    <a class="btn btn-primary" href="{% url 'mailings:message_update' object.pk %}">Изменить</a>
                {% else %}
                {% endif %}
                {% if perms.mailings.delete_message %}
                    <a class="btn btn-danger" href="{% url 'mailings:message_delete' object.pk %}">Удалить</a>
                {% else %}
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}