blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    content = models.TextField(verbose_name='Содержимое')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата публикации')
    is_published = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.IntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title} (создано {self.created_at})'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/forms.py
from django import forms

from blog.models import Blog
from mailings.forms import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        exclude = ["date", "author"]

blog/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from blog.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', )
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_content = form.save(commit=False)
            new_content.slug = slugify(new_content.title)
            new_content.author = self.request.user
            new_content.save()

        return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', )

    def form_valid(self, form):
        if form.is_valid():
            new_content = form.save()
            new_content.slug = slugify(new_content.title)
            new_content.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')


def toggle_activity(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    blog_item.is_published = False if blog_item.is_published else True

    blog_item.save()
    return redirect(reverse('blog:list'))

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}
<main role="main">

    <h1 class="display text-center mt-4">{{ object.title }}</h1>

    <div class="col-12 d-flex justify-content-center align-items-center">
        <div class="card d-flex justify-content-center">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>Вы действительно хотите удалить "{{ object.title }}"?</p>
                    <button class="btn btn-danger" type="submit">Подтвердить</button>
                    <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                </form>
            </div>
        </div>
    </div>
</main>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailings/base.html' %}
{% block content %}

<h1 class="display text-center mt-4">{{ object.title }}</h1>



<div class="container">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <p>{{ object.content }}</p>
            <ul class="list-unstyled mt-3 mb-2 text-start m-2">
                <li>- Создан {{ object.created_at }}</li>
                <li>- Количество просмотров: {{ object.views_count }}</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<main role="main">
    <div class="col-12">
        <div class="container">
            <h2 class="display-4">Заполните поля формы</h2>
        </div>
    </div>
    <div class="col-5">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button class="btn btn-primary w-100" type="submit">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailings/base.html' %}
{% block content %}
<main role="main">
    <div class="col-12">
        <div class="container px-5 py-5 pt-md-5 pb-md-5 mx-auto text-center">





            {% if user.is_authenticated %}
                <a href="{% url 'blog:create' %}" class="btn btn-primary form-control" >Добавить запись</a>
            {% else %}
                <a class="btn btn-primary form-control" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button"
                    aria-expanded="false" aria-controls="multiCollapseExample1">Добавить продукт</a>
            <div class="col">
                <div class="collapse multi-collapse mb-5" id="multiCollapseExample1">
                    <div class="card card-body mb-5">
                        <h3>Войдите в свой аккаунт или зарегистрируйтесь, чтобы добавить запись в блог!</h3>
                    </div>
                </div>
            </div>
        {% endif %}
        </div>
    </div>
    <div class="container mb-5">
        <div class="row">
            {% for object in object_list %}
            <div class="card mb-4 mr-5" style="width: 20rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ object.title }}</h5>
                    <p class="card-text">{{ object.content|slice:100 }} </p>
                    <a href="{% url 'blog:view' object.pk %}" class="btn btn-sm btn-outline-primary" role="button">Посмотреть</a>
                    <a href="{% url 'blog:update' object.pk %}" class="btn btn-sm btn-outline-primary">Изменить</a>
                    <a href="{% url 'blog:delete' object.pk %}" class="btn btn-sm btn-outline-danger">Удалить</a>
                </div>
                <a class="btn btn-warning" href="{% url 'blog:toggle_activity' object.pk %}">Снять публикацию</a>
            </div>
            {% endfor %}
        </div>
    </div>
</main>

{% endblock %}