blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView, toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailings.urls', namespace='mailings')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailings.apps import MailingsConfig
from mailings.views import *

app_name = MailingsConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('mailings/list/', cache_page(60)(MailingsListView.as_view()), name='mailings_list'),
    path('mailings/<int:pk>/', MailingsDetailView.as_view(), name='mailings_detail'),
    path('mailings/create/', MailingsCreateView.as_view(), name='mailings_create'),
    path('mailings/<int:pk>/update/', MailingsUpdateView.as_view(), name='mailings_update'),
    path('mailings/<int:pk>/delete/', MailingsDeleteView.as_view(), name='mailings_delete'),
    path('client/', cache_page(60)(ClientListView.as_view()), name='client_list'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('contacts/', ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('message/', cache_page(60)(MessageListView.as_view()), name='message_list'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='message_detail'),
    path('message/create/', MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='message_delete'),
    path('mailings/<int:pk>/toggle_activity', toggle_activity, name='mailing_toggle_activity'),
    path('logs/', LogListView.as_view(), name='logs'),
    path('logs/<int:pk>/', get_mailing_logs, name='mailing_logs'),
    path('contacts/', ContactsView.as_view(), name='contacts')
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, reset_password, verify_email, UserListView, toggle_activity

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('verify/<str:token>/', verify_email, name='verify'),
    path('reset_password/', reset_password, name='reset_password'),
    path('user/', UserListView.as_view(), name='list'),
    path('activity/<int:user_id>', toggle_activity, name='toggle_activity'),
    ]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(max_length=100, verbose_name='Почта', unique=True)
    phone = models.CharField(max_length=20, verbose_name='Телефон', **NULLABLE)
    country = models.CharField(max_length=20, verbose_name='Страна', **NULLABLE)
    token = models.CharField(max_length=100, **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

        permissions = [
            (
                'set_activity',
                'Can change activity'
            )
        ]

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from mailings.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'password', 'phone', 'country', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class UserAuthenticationForm(StyleFormMixin, AuthenticationForm):
    class Meta:
        model = User
        fields = ('email', 'password')

users/views.py
import random
import string

from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User
from django.contrib.auth.models import Group


class RegisterView(SuccessMessageMixin, CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        token = ''.join(random.sample(string.digits + string.ascii_letters, 12))
        self.object.token = token
        self.object.is_active = False
        self.object.save()
        url = 'http://127.0.0.1:8000/users/verify/' + token

        if form.is_valid():
            send_mail(
                subject='Подтверждение регистрации',
                message=f"""Для подтверждения регистрации и присоединении к команде перейдите по ссылке: {url}
                        Внимание! Если вы не понимаете, почему Вам пришло это письмо, просто проигнорируйте его""",
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[self.object.email]
            )
        group = Group.objects.get(name='users')
        group.user_set.add(self.object)
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_user'


def verify_email(request, token):
    user = User.objects.filter(token=token).first()
    if user:
        user.is_active = True
        user.save()
        messages.success(request, 'Пользователь подтвержден')
    else:
        messages.error(request, 'Пользователь с таким e-mail не найден')
    return redirect('users:login')


def reset_password(request):
    if request.method == 'POST':
        input_email = request.POST.get('email')
        user = User.objects.filter(email=input_email).first()
        if user:

            password = User.objects.make_random_password()
            user.set_password(password)
            user.save(update_fields=['password'])
            send_mail(
                subject='Сброс пароля',
                message=f'''Вы успешно сбросили пароль для аккаунта {input_email}.\n Ваш новый пароль: {password}''',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[input_email]
            )
        else:
            messages.error(request, 'Пользователь с таким e-mail не найден')
    return render(request, 'users/reset_password.html')


@permission_required('users.set_activity')
@login_required
def toggle_activity(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    if request.user.is_staff:
        if user.is_active and not user.is_superuser:
            user.is_active = False
            user.save()
        else:
            user.is_active = True
            user.save()
        return redirect('users:list')

users/templates/users/login.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="col-12">
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-3"></div>
        <div class="col-4">

                <div class="col-4" style="width: 20rem;">
                    <h3 class="card-title">
                      Вход
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        Войти
                    </button>
                    <a href="{% url 'users:reset_password' %}" class="btn btn-outline-primary">Восстановить пароль</a>
                </div>
            </div>
</form>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="col-12">
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                      Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        Регистрация
                    </button>
                </div>
            </div>
        </div>

</form>
</div>
{% endblock %}

users/templates/users/reset_password.html
{% extends 'mailings/base.html' %}

{% block content %}
        <div class="col-12">
            <form method="post" enctype="multipart/form-data" class="row mt-5">
                <div class="col-4"></div>
                <div class="col-4 ml-5">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Сброс пароля
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <input type="text" name="email" class="form-control mb-2" id="email"
                                   placeholder="Введите email"
                                   required>
                            <button class="btn btn-danger" type="submit">
                                Подтвердить
                            </button>
                            <a href="{% url 'users:login' %}" class="btn btn-warning">Отмена</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="col-12">
<form method="post" class="row" enctype="multipart/form-data">
    <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                      Профиль
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        Сохранить
                    </button>
                </div>
            </div>
        </div>

</form>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailings/base.html' %}

{% block content %}

    <div class="container">
        <div class="row my-5">

            <table class="table table-striped table-bordered">
                <caption style="caption-side: top">Список пользователей</caption>
                <thead>
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Email</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Фамилия</th>
                    <th scope="col">Страна</th>
                    <th scope="col">Дата рождения</th>
                    <th scope="col">Активность</th>
                    <th scope="col">Сменить статус</th>
                </tr>
                </thead>
                <tbody class="table-group-divider">
                {% for object in object_list %}
                    <tr>
                        <th scope="row">
                            <a href="{% url 'mailings:client_detail' object.pk %}">{{ object.pk }}</a>
                        </th>
                        <td>{{ object.email }}</td>
                        <td>{{ object.first_name }}</td>
                        <td>{{ object.last_name }}</td>
                        <td>{{ object.country }}</td>
                        <td>{{ object.birthday }}</td>
                        <td>{% if object.is_active %}Активен{% else %}Не активен{% endif %}</td>
                        <td>
                            {% if perms.users.set_activity %}
                                {% if not object.is_superuser %}
                                    {% if object.is_active %}
                                        <a href="{% url 'users:toggle_activity' object.pk %}"
                                           class="btn btn-outline-danger">Заблокировать</a>
                                    {% else %}
                                        <a href="{% url 'users:toggle_activity' object.pk %}"
                                           class="btn btn-outline-success">Разблокировать</a>
                                    {% endif %}
                                {% endif %}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>

{% endblock %}

users/templates/users/verify_email.html
{% extends 'mailings/base.html' %}

{% block content %}
    <main role="main">

        <div class="col-12">
            <form method="post" enctype="multipart/form-data" class="row mt-5">
                <div class="col-4"></div>
                <div class="col-4 ml-5">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                Подтвердите электронную почту
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class="btn btn-success" type="submit">
                                Подтвердить
                            </button>
                            <a href="{% url 'users:login' %}" class="btn btn-danger">Отмена</a>

                        </div>
                    </div>
                </div>
            </form>
        </div>

        <hr>

    </main>

{% endblock %}